---
deployment:
  tasks:
    - export DEPLOYPATH=/home/luckbepo/notes
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp server.js $DEPLOYPATH 
    - /bin/cp package.json $DEPLOYPATH 
    - /bin/cp package-lock.json $DEPLOYPATH 